### ISSUE TITLE
Possible to install agent without starting it up?

### ISSUE THREAD

**Issue by luckytaxi** [DataDog/chef-datadog#447]
We build AMI images for all of our apps. I want to speed up the Chef run on firstboot once the ec2 instance comes up. I notice installing the datadog agent takes a bit of time so I wanted to move that piece into the Packer build. How can I go about installing the agent but not have it start and send metrics to Datadog?

**Comment by luckytaxi** [comment]
It just occurred to me that I could install the RPM package within my Packer script. Since the config file isn't present, the service shouldn't start.

**Comment by aidanmelen** [comment]
did you try using the agent_start property? Here is an example of how to use it:

``` yaml
- name: dd-agent
  run_list:
    - recipe[datadog::dd-agent]
  attributes:
    datadog: &DATADOG
      api_key: somethingnotnil
      application_key: alsonotnil
      agent_start: false
```

**Comment by luckytaxi** [comment]
Doesn't work unless I'm setting it incorrectly. I'm setting this in my role.

```
 "default_attributes": {
    "datadog" : {
      "agent_start" : false
    }
  },
  "override_attributes": {
  },
  "chef_type": "role",
  "run_list": [
    "recipe[datadog::dd-agent]",
```

**Comment by mbaxa** [comment]
I'll chime in that I have this problem too:
From my kitchen.yml
```yml
datadog:
   agent_start: false
   agent_enable: false
   enable_process_agent: true
```

From the instance:
```bash
$ ps aux | grep ddagent
dd-agent  8747  0.2  0.2 173236 43260 ?        S    18:03   0:03 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/ddagent.py
```
