### ISSUE TITLE
problem adding thresholds ['datadog']['process']['instances']

### ISSUE THREAD

**Issue by cmessinaclearchannel** [DataDog/chef-datadog#494]
I am attempting and failing to add a threshold to a process monitor.

```
node.override['datadog']['process']['instances'] = [
    {   
        'name' => 'myprocess', 
        'search_string' => ['myprocess'],
        'tags' => [ 'foo', 'monitor:myprocess' ], 
        'thresholds' => { 'critical' => [8, 15] }
    }
]  
```

Since the templates are converting the instance to json and the json to yaml, I believe that is the right syntax, however the end result is yaml that defines 

what I get:
```
---
instances:
- name: myprocess
  search_string:
  - "myprocess"
  tags:
  - foo
  - monitor:myprocess
  thresholds:
  - critical:
    - 8
    - 15
```

What I want:
```
---
instances:
- name: myprocess
  search_string:
  - "myprocess"
  tags:
  - foo
  - monitor:myprocess
  thresholds:
    critical:
    - 8
    - 15
```

Note that "critical" should not be a list item.

Is my syntax wrong?  Can anyone show me the correct syntax for this so the process.yaml meets the syntax requirements defined here: https://docs.datadoghq.com/integrations/process/

Thanks.
