### ISSUE TITLE
logs_config missing from datadog.yaml.erb

### ISSUE THREAD

**Issue by wzcwts521** [DataDog/chef-datadog#553]
```
ERROR | (start.go:190 in StartAgent) | Could not start logs-agent:  could not find any valid logs configuration
```
Agent version 6.4.2
```
Agent 6.4.2 - Commit: 155fddb - Serialization version: 4.7.1
```
datadog.yml file. 
```
# Generated by Chef, local modifications will be overwritten

---
api_key: xxxxxx
dd_url: https://app.datadoghq.com
hostname: pso-dev-042.xxxxxxx
bind_host: localhost
additional_endpoints: {}
tags:
- team:pe
dogstatsd_non_local_traffic: true
histogram_aggregates:
- max
- median
- avg
- count
histogram_percentiles:
- '0.95'
use_dogstatsd: true
log_level: INFO
logs_enabled: true
process_config:
  enabled: 'true'
  intervals: {}
  blacklist_patterns: []
  scrub_args: true
  custom_sensitive_words: []
  process_dd_url: https://process.datadoghq.com
log_file: "/var/log/datadog/agent.log"
apm_config:
  enabled: true
  apm_non_local_traffic: true
```

https://github.com/DataDog/chef-datadog/blob/971791e7fba30e072d3f05edc6a5523155275b1c/templates/default/ @datadog.yaml.erb#L91-L92

seems like missing following format
```

logs_config:
  container_collect_all: false
  dd_port: 10516
  dd_url: agent-intake.logs.datadoghq.com
  dev_mode_use_proto: true
  open_files_limit: 100
  run_path: /opt/datadog-agent/run
logs_enabled: true
logset: ""
```
