### ISSUE TITLE
Escape Characters in log collector config

### ISSUE THREAD

**Issue by kymagic** [DataDog/chef-datadog#578]
The cookbook isn't handling escape characters correctly when specifying log collector configurations.

I'm trying to set multi-line log aggregation rules for Nginx, which requires a regex:

```
node.override['datadog']['nginx']['logs'] = [
  {
    'type' => 'file',
    'path' => '/var/log/nginx/access.log',
    'service' => 'nginx',
    'source' => 'nginx',
    'log_processing_rules' => [
      {
        'type' => 'multi_line',
        'name' => 'new_lines_start_with_ip',
        'pattern' => '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
      }
    ]
  }
]
```
But the YAML config generated by this is as follows:

```
---
logs:
- type: file
  path: "/var/log/nginx/access.log"
  service: nginx
  source: nginx
  log_processing_rules:
  - type: multi_line
    name: new_lines_start_with_ip
    pattern: "\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}"
```

I've tried double- and single-quotes, and whether to double- or single- escape the characters that need escaping, but the only two possible outputs are `"\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}"` or `"d{1,3}.d{1,3}.d{1,3}.d{1,3}"`.

It looks like it might be to do with the way that the YAML is generated by converting it to JSON, parsing the JSON, and converting that to YAML. 

A workaround would be to use `[0-9]` and `[.]` instead, but this isn't intuitive.
