### ISSUE TITLE
SOLR Integration doesn't work when configured with Chef

### ISSUE THREAD

**Issue by RulerOf** [DataDog/chef-datadog#790]
When I configure the integration with SOLR, it writes [this YAML config](https://github.com/DataDog/chef-datadog/blob/785af6cbbc11c0e1afb759e9005e07002a61047e/templates/default/solr.yaml.erb) which is nothing at all like the [documentation for the solr integration](https://docs.datadoghq.com/integrations/solr/?tab=host).  After applying the chef config and checking DataDog, I have no metrics matching `solr`.

I manually modify the conf.yaml to this and it works great:
```yaml
# Generated by Chef, local modifications will be overwritten

---
instances:
- host: localhost
  port: 18983
logs: []

init_config:
  is_jmx: true
  collect_default_metrics: true
```

Did the integration change and the chef recipe was never updated?
