### ISSUE TITLE
logs_agent_config attribute is ignored

### ISSUE THREAD

**Issue by axl89** [DataDog/chef-datadog#800]
This issue seems related with #704 .

When having a datadog role like the following one, the `/etc/datadog-agent/datadog.yaml` does not print the `logs_agent_config` section:

### Role

```json
{
    "name": "datadog",
    "description": "Installs Datadog agent",
    "default_attributes": {
        "datadog": {
            "api_key": "xx",
            "application_key": "yy",
            "enable_process_agent": true,
            "enable_logs_agent": true,
            "logs_agent_config": {
                "container_collect_all": true
            },
            "collect_ec2_tags": true,
            "system_probe": {
                "network_enabled": true
            },
            "enable_trace_agent": true,
            "extra_config": {
                "runtime_security_config": true,
                "compliance_config": true,
                "fim_enabled": true,
                "syscall_monitor": true
            }
        }
    },
    "run_list": [
        "recipe[datadog::dd-agent]",
        "recipe[datadog::dd-handler]"
    ]
}
```

### Obtained datadog.yaml

```yaml
# Generated by Chef, local modifications will be overwritten

---
runtime_security_config: true
compliance_config: true
fim_enabled: true
syscall_monitor: true
api_key: xx
site: datadoghq.eu
hostname: wutwut
bind_host: localhost
additional_endpoints: {}
tags: []
collect_ec2_tags: true
dogstatsd_non_local_traffic: false
histogram_aggregates:
- max
- median
- avg
- count
histogram_percentiles:
- '0.95'
use_dogstatsd: true
log_level: INFO
logs_enabled: true
log_file: "/var/log/datadog/agent.log"
process_config:
  enabled: 'true'
  intervals: {}
  blacklist_patterns: []
  scrub_args: true
  custom_sensitive_words: []
  process_dd_url: https://process.datadoghq.com
apm_config:
  enabled: true
  apm_non_local_traffic: false
```
