### ISSUE TITLE
network: passing multiple instances to network monitor increases counts

### ISSUE THREAD

**Issue by miketheman** [DataDog/chef-datadog#98]
Currently, the method for passing a `network` config matches all others, however this adds to the instances array.
This should not map to the same, rather only a single entry can work for monitoring the network state of an instance.

a role:

```
default_attributes(
  'datadog' => {
    'network' => {
      'instances' => [
        {
          'collect_connection_state' => 'true',
          'excluded_interfaces' => ['lo', 'lo0']
        }
      ]
    }
  },
)
```

Along with the default attributes file `network.rb` will result in the following yaml:

``` yaml
init_config:

instances:
 - collect_connection_state: false
   excluded_interfaces:
     - lo
     - lo0
 - collect_connection_state: true
   excluded_interfaces:
     - lo
     - lo0
```
